version: 6.33.4

type: DeclarativeSource

check:
  type: CheckStream
  stream_names:
    - paris-events-explore

definitions:
  streams:
    paris-events-export:
      type: DeclarativeStream
      name: paris-events-export
      retriever:
        type: SimpleRetriever
        requester:
          $ref: "#/definitions/base_requester"
          path: explore/v2.1/catalog/datasets/que-faire-a-paris-/exports/json
          http_method: GET
          request_parameters:
            where: updated_at > "2025-01-01T00:00:00+00:00"
            select: id,url,title,lead_text,description,date_start,date_end
        record_selector:
          type: RecordSelector
          extractor:
            type: DpathExtractor
            field_path: []
      primary_key:
        - id
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/paris-events-export"
    paris-events-explore:
      type: DeclarativeStream
      name: paris-events-explore
      retriever:
        type: SimpleRetriever
        requester:
          $ref: "#/definitions/base_requester"
          path: explore/v2.1/catalog/datasets/que-faire-a-paris-/records
          http_method: GET
          request_parameters:
            limit: "100"
            where: updated_at > "2025-01-01T00:00:00+00:00"
            select: id,url,title,lead_text,description,date_start,date_end
        record_selector:
          type: RecordSelector
          extractor:
            type: DpathExtractor
            field_path:
              - results
      primary_key:
        - id
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/paris-events-explore"
  base_requester:
    type: HttpRequester
    url_base: https://opendata.paris.fr/api/

streams:
  - $ref: "#/definitions/streams/paris-events-explore"
  - $ref: "#/definitions/streams/paris-events-export"

spec:
  type: Spec
  connection_specification:
    type: object
    $schema: http://json-schema.org/draft-07/schema#
    required: []
    properties: {}
    additionalProperties: true

metadata:
  assist: {}
  testedStreams:
    paris-events-export:
      hasRecords: true
      streamHash: cb15b09ef6a8c1aa645f15af5b41b86f5da9c4c3
      hasResponse: true
      primaryKeysAreUnique: true
      primaryKeysArePresent: true
      responsesAreSuccessful: true
    paris-events-explore:
      hasRecords: true
      streamHash: 069daa095f6f6416e6e35c0c8f380f7c369dbd27
      hasResponse: true
      primaryKeysAreUnique: true
      primaryKeysArePresent: true
      responsesAreSuccessful: true
  autoImportSchema:
    paris-events-export: true
    paris-events-explore: true

schemas:
  paris-events-export:
    type: object
    $schema: http://json-schema.org/schema#
    required:
      - id
    properties:
      description:
        type:
          - string
          - "null"
      id:
        type: string
      url:
        type:
          - string
          - "null"
      title:
        type:
          - string
          - "null"
      date_end:
        type:
          - string
          - "null"
      lead_text:
        type:
          - string
          - "null"
      date_start:
        type:
          - string
          - "null"
    additionalProperties: true
  paris-events-explore:
    type: object
    $schema: http://json-schema.org/schema#
    required:
      - id
    properties:
      description:
        type:
          - string
          - "null"
      id:
        type: string
      url:
        type:
          - string
          - "null"
      title:
        type:
          - string
          - "null"
      date_end:
        type:
          - string
          - "null"
      lead_text:
        type:
          - string
          - "null"
      date_start:
        type:
          - string
          - "null"
    additionalProperties: true
